# Generated by Django 5.1.2 on 2024-10-25 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update_at", models.DateTimeField(auto_now=True)),
                ("api_token", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("openID", models.IntegerField()),
                ("token", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update_at", models.DateTimeField(auto_now=True)),
                ("externalID", models.CharField(max_length=255)),
                (
                    "companyID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zapsign_app.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Signers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("externalID", models.CharField(max_length=255)),
                (
                    "documentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zapsign_app.document",
                    ),
                ),
            ],
        ),
    ]
