# Generated by Django 5.1.2 on 2024-10-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zapsign_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="original_file",
            field=models.CharField(
                default="https://ebac-homepage.vercel.app/image-host/ZAP-Document.pdf",
                max_length=500,
            ),
        ),
    ]
