# Generated by Django 5.1.2 on 2024-10-28 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zapsign_app", "0002_document_original_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signers",
            old_name="documentID",
            new_name="document_openID",
        ),
    ]
