# Generated by Django 5.1.2 on 2024-10-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zapsign_app", "0003_rename_documentid_signers_document_openid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signers",
            old_name="document_openID",
            new_name="documentID",
        ),
    ]
